console.log('🔍 Debug Info:');
console.log('================');
console.log('Server:', 'http://localhost:5173');
console.log('');
console.log('📝 Steps to debug:');
console.log('1. Mở browser: http://localhost:5173');
console.log('2. Mở DevTools (F12)');
console.log('3. Tab Console - xem có error gì không');
console.log('4. Tab Network - check failed requests');
console.log('');
console.log('🎯 Test URLs:');
console.log('- Home: http://localhost:5173/');
console.log('- Admin: http://localhost:5173/admin');
