services:
  gao-st25-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - gao-st25-network

networks:
  gao-st25-network:
    driver: bridge

